services:
  postgres-test:
    image: postgres:15-alpine
    container_name: workout-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: workout_test
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d workout_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx-test:
    image: nginx:alpine
    container_name: workout-test-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres-test
    restart: unless-stopped

volumes:
  postgres-test-data:
