name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: workout_test
      NODE_ENV: test
      PORT: 5001
      CORS_ORIGIN: https://localhost
      OPENAI_API_KEY: test_key_for_ci
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: workout_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build frontend
      run: npm run build
    
    - name: Generate SSL certificates
      run: |
        mkdir -p nginx/certs
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout nginx/certs/localhost.key \
          -out nginx/certs/localhost.crt \
          -subj "/C=US/ST=State/L=City/O=CI/CN=localhost" \
          -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
        echo "SSL certificates generated"
    
    - name: Start nginx container
      run: |
        docker run -d \
          --name workout-test-nginx \
          -p 80:80 \
          -p 443:443 \
          --add-host=host.docker.internal:host-gateway \
          -v $(pwd)/nginx/nginx.ci.conf:/etc/nginx/nginx.conf:ro \
          -v $(pwd)/nginx/certs:/etc/nginx/certs:ro \
          nginx:alpine
        echo "Nginx container started with CI config"
    
    - name: Set up test database
      run: |
        cd server
        npm run db:migrate
    
    - name: Start backend server (serves built frontend + API)
      run: |
        cd server
        npm start > ../backend.log 2>&1 &
        echo $! > ../server.pid
        echo "Backend server started with PID $(cat ../server.pid)"
    
    - name: Wait for servers to be ready
      run: |
        echo "Waiting for backend server on port 5001..."
        for i in {1..60}; do
          if curl -f http://localhost:5001/ 2>/dev/null; then
            echo "Backend server is ready and serving frontend!"
            break
          fi
          if [ $i -eq 60 ]; then
            echo "Backend server failed to start. Logs:"
            cat backend.log || echo "No backend.log found"
            exit 1
          fi
          sleep 1
        done
        
        echo "Waiting for nginx on port 443..."
        for i in {1..30}; do
          if curl -k -f https://localhost 2>/dev/null; then
            echo "Nginx is ready!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Nginx failed to start"
            docker logs workout-test-nginx || echo "No nginx logs"
            exit 1
          fi
          sleep 1
        done
        
        echo "All servers are ready!"
    
    - name: Run Playwright tests
      run: npm run test:e2e
    
    - name: Stop servers
      if: always()
      run: |
        if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
        docker stop workout-test-nginx || true
        docker rm workout-test-nginx || true
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
